"""Big file to dump big localization constants in"""
from locale import normalize

DEFAULT_LOCALE = normalize("en")

# This was generated by calling set() on the en file.
STRINGS_SUPPORTED = {
    "GLOBAL",
    "LOCAL",
    "both",
    "completion_message",
    "context_prompt",
    "copied",
    "cwd",
    "default_context_name_name",
    "default_context_name_prompt",
    "default_knowns_name",
    "default_knowns_response",
    "default_steps",
    "default_title",
    "edit_destination_prompt",
    "edit_extension_prompt",
    "edit_name_prompt",
    "edit_open_editor_prompt",
    "edit_title_prompt",
    "file_edited",
    "file_written",
    "filename_prompt",
    "help",
    "home",
    "missing_file_warn",
    "nag",
    "new_destination_prompt",
    "new_extension_prompt",
    "new_extra_config_prompt",
    "new_open_editor_prompt",
    "new_title_prompt",
    "overwrite_warn",
    "step_prefix",
    "stylish_interjection",
}
